# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c06cbc16b73154bbd643e475bf2e05400115ea0832900d5b983f4e9700358b82864f21479df75b507eb374e45ee2c25a9bdda316730327ca60acbadb14e19954

test:
  secret_key_base: 6ff202065a7e1ac3b837fad3cac6e6b3c49754222438fc6c162dc43194775211b3c60a69b7809f94e321c12399b950517fa7fdd08df8aa262c03d3af563c838c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
